/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sicor.view;

import br.com.sicor.classes.Criptografia;
import br.com.sicor.classes.Dados;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.Properties;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Debug
 */
public class DialogAtivacao extends javax.swing.JDialog {

    private boolean ativa;
    private String code1;
    private String code2;
    Dados dados;
    Properties prop;

    public String getCode1() {
        return code1;
    }

    public void setCode1(String code1) {
        this.code1 = code1;
    }

    public String getCode2() {
        return code2;
    }

    public void setCode2(String code2) {
        this.code2 = code2;
    }
    
    public boolean isAtiva() {
        return ativa;
    }

    public void setAtiva(boolean ativa) {
        this.ativa = ativa;
    }
    
    /**
     * Creates new form DialogAtivacao
     */
    public DialogAtivacao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        labelMensagem.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        textCode1 = new javax.swing.JTextField();
        labelTraco = new javax.swing.JLabel();
        textCode2 = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        labelMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Ativação do sistema SICOR");

        labelCodigo.setText("Código: ");

        textCode1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textCode1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textCode1KeyReleased(evt);
            }
        });

        labelTraco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTraco.setText("-");

        textCode2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textCode2KeyPressed(evt);
            }
        });

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicor/images/icon16x16Salvar.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sicor/images/cancelar.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        labelMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMensagem.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMensagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btCancelar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTraco, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(textCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigo)
                    .addComponent(textCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTraco)
                    .addComponent(textCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        this.salvarCode();
    }//GEN-LAST:event_btSalvarActionPerformed

    public void salvarCode(){
        dados = new Dados();
        prop = new Properties();
        
        Locale locale = new Locale("pt", "BR");
        Calendar cal = Calendar.getInstance(locale);

        cal.add(Calendar.DAY_OF_MONTH, 7);
        
        int dia = cal.get(Calendar.DAY_OF_MONTH);
        int mes = cal.get(Calendar.MONTH) + 1;
        int ano = cal.get(Calendar.YEAR);
        
        String endMac = dados.mac();
        String nomeArquivo = "config.properties";
        String path = "C:\\Sicor\\config\\";
        
        String campo1 = textCode1.getText();
        String campo2 = textCode2.getText();
        
        String codigo = campo1 + " - " + campo2;
        String cript = null;
        try{
            String pastaSistema = "C:\\Sicor";
            int quantidade = Integer.valueOf(prop.getProperty("prop.server.qtde"));
            if(codigo.equals("CC015 - 123") || codigo.equals("cc015 - 123")){
                String novaData = String.valueOf(dia + "/" + mes + "/" + ano);
                prop.setProperty("prop.server.validade", novaData);
                if(quantidade <= 3){
                    cript = Criptografia.criptografa("true");
                    prop.setProperty("prop.server.qtde", String.valueOf(quantidade + 1));
                    prop.setProperty("prop.server.original", cript);
                }else{
                    cript = Criptografia.criptografa("false");
                    JOptionPane.showMessageDialog(null, "Excedido o limite do código de ativação.");
                    prop.setProperty("prop.server.original", "false");
                }

            }else if(codigo.equals("SM999 - 999")){
                cript = Criptografia.criptografa("true");
                prop.setProperty("prop.server.validade", "indefinido");
                prop.setProperty("prop.server.original", cript);
                
            }
                prop.setProperty("prop.server.mac", endMac);
                prop.setProperty("prop.server.codativacao", codigo);
                prop.setProperty("prop.server.autorizada", "true");
                prop.setProperty("prop.server.path", path);
                prop.setProperty("prop.server.pathSistema", pastaSistema);

                prop.store(new FileOutputStream(path + nomeArquivo), "prop.server");

                labelMensagem.setVisible(true);
                labelMensagem.setText("Salvo com sucesso!");
            
        } catch (FileNotFoundException ex) {
                System.out.println("Erro File Not Found: " + ex.getMessage());
            } catch (IOException ex) {
                System.out.println("Erro IOException: " + ex.getMessage());
            }
        
    }
    
    private void textCode1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCode1KeyPressed

        this.proximoCampo(evt, textCode2);
        // TODO add your handling code here:
    }//GEN-LAST:event_textCode1KeyPressed

    private void textCode1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCode1KeyReleased
        this.proximoCampo(evt, textCode2);
        // TODO add your handling code here:
    }//GEN-LAST:event_textCode1KeyReleased

    private void textCode2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCode2KeyPressed
        this.proximoBotao(evt, btSalvar);
        // TODO add your handling code here:
    }//GEN-LAST:event_textCode2KeyPressed

    public void proximoCampo(KeyEvent evt, JTextField campo){
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            campo.requestFocus();
        }
        
    }
    
    public void proximoBotao(KeyEvent evt, JButton botao){
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            botao.addActionListener(
                new ActionListener() {
                    public void actionPerformed( ActionEvent ae ) {
                        salvarCode();
                    }
                }
            );
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogAtivacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogAtivacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogAtivacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogAtivacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogAtivacao dialog = new DialogAtivacao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelMensagem;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTraco;
    private javax.swing.JTextField textCode1;
    private javax.swing.JTextField textCode2;
    // End of variables declaration//GEN-END:variables
}
